# Generated by Django 3.0.2 on 2020-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnumbers',
            name='TelegramId',
            field=models.CharField(default='', max_length=20),
        ),
    ]
