# Generated by Django 3.0.2 on 2020-03-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200323_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretTikens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameApp', models.CharField(max_length=255)),
                ('SecretToken', models.CharField(max_length=255)),
            ],
        ),
    ]
