# Generated by Django 3.0.2 on 2020-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_secrettikens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecretTikens',
            new_name='SecretTokens',
        ),
        migrations.AddField(
            model_name='numbers',
            name='NumberName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
